### ISSUE TITLE
Mashup doesn't install rules

### ISSUE THREAD

**Issue by giovannicuriel** [dojot/mashup#3]
When [this description](https://gist.github.com/giovannicuriel/26e49af64e600a9a1fef21bbf6a28963) is sent to mashup, its log shows the following output:

```
mashup_1          | Sending Perseo rules creation request...                                                         
mashup_1          | Perseo rules creation request were sent.                                                         
mashup_1          | Updating database with new subscription ID and Perseo rules...                                   
mashup_1          | Starting Orion subscription callback (V2).                                                                                                                                                                             
mashup_1          | Results are: error: null, status code is 201                                                     
mashup_1          | Generating Perseo rules...            
mashup_1          | 30 Aug 16:45:50 - [red] Uncaught Exception:                                                      
mashup_1          | 30 Aug 16:45:50 - TypeError: Cannot read property 'translatedTemplate' of undefined              
mashup_1          |     at transformToPerseoRequest (/usr/src/node-red/orchestrator/translator.js:703:48)            
mashup_1          |     at Object.generatePerseoRequest (/usr/src/node-red/orchestrator/translator.js:821:12)        
mashup_1          |     at orionSubscriptionCallbackV2 (/usr/src/node-red/orchestrator/orchestrator.js:61:36)                                                                                                                              
mashup_1          |     at Request._callback (/usr/src/node-red/orchestrator/orchestrator.js:104:9)                                                                                                                                        
mashup_1          |     at Request.self.callback (/usr/src/node-red/node_modules/request/request.js:188:22)                                                                                                                                
mashup_1          |     at emitTwo (events.js:106:13)                                                                                                                                                                                      
mashup_1          |     at Request.emit (events.js:194:7)                                                                                                                                                                                  
mashup_1          |     at Request.<anonymous> (/usr/src/node-red/node_modules/request/request.js:1171:10)                                                                                                                                 
mashup_1          |     at emitOne (events.js:96:13)                                                                                                                                                                                       
mashup_1          |     at Request.emit (events.js:191:7)   
```

And the node reboots.

**Comment by giovannicuriel** [comment]
As mashup will be reengineered, I'll close this issue (this problem is particular to current implementation)
